spring.application.name=RiskManagementSystem
spring.datasource.url=jdbc:mysql://localhost:3306/risk_management_system
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

gemini.api.key=AIzaSyAD5k1UEqIwzsD0U5Wm-QH97QFlcy75gUA
gemini.model=gemini-3-flash-preview
spring.devtools.restart.enabled=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noreply.chainguard@gmail.com
spring.mail.password=bxfd pyyo nadc giia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.session.timeout=30m